# -*- coding: utf-8 -*-
"""Task5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1A0R__ArMa5QLDujViHayF6oOUTgJqLXY
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import folium
from folium.plugins import MarkerCluster

df = pd.read_csv('/content/sample_data/RTA Dataset.csv')

df

df.head()

df.tail()

df.shape

df.columns

df.dtypes

print(df.isnull().sum())
df = df.dropna()

# Countplot for road conditions
plt.figure(figsize=(12, 6))
sns.countplot(x='Road_surface_type', data=df)
plt.title('Distribution of Road Conditions')
plt.xticks(rotation=45)
plt.show()

# Countplot for time of day
plt.figure(figsize=(12, 6))
sns.countplot(x='Time', data=df)
plt.title('Distribution of Accidents by Time of Day')
plt.xticks(rotation=45)
plt.show()

# Countplot for accidents by day of the week
plt.figure(figsize=(12, 6))
sns.countplot(x='Day_of_week', data=df)
plt.title('Distribution of Accidents by Day of the Week')
plt.xticks(rotation=45)
plt.show()